### PR TITLE
3 feature 1 account creation

### PR DESCRIPTION
**Pull request by e-2003**
Added the layers for the User use case, implemented some UI frames and linked the screens.

### CODE REVIEW

**Review by nomiko0626 — APPROVED** [review]

**Review by royjin1 — APPROVED** [review]

**Review by nomiko0626 — DISMISSED** [review]
Looks good.

**Review by royjin1 — APPROVED** [review]
One user can only have one pet now, and the petID is saved as"PetID: 1" in the database.

**Review by shirleywu915 — DISMISSED** [review]
Most of them look good! 
Some suggestions for changes to the PreferenceEdit Screen:
1. AgeChoice: we should ask the user to input numbers rather than selecting from a list of ages
2. GenderChoice should also have a "no preference" choice.
3. Should have more clear labels for each section that's asking for user input
4. Need to link to the controller and database.

But this pull request if good to be merged right now, we can fix these and add to it if we have time later.

**Review by royjin1 — COMMENTED** [review]
When the user is created the initializer might need more information.

**Review by nomiko0626 — APPROVED** [review]
Everything looks good to be merged to main!

**Pull request merged**
